# coding: utf-8

"""
    REGNIFY HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: admin@regnify.com
    Generated by: https://openapi-generator.tech
"""

from regnify.paths.roles_role_id_assign_role.post import AssignRole
from regnify.paths.roles_.post import CreateRole
from regnify.paths.roles_role_id.delete import DeleteRole
from regnify.paths.roles_role_id.put import EditRole
from regnify.paths.roles_role_id.get import GetRole
from regnify.paths.roles_.get import GetRoles
from regnify.paths.roles_role_id_list_assigned_users.get import ListUsersAssignedToRole
from regnify.paths.roles_role_id_unassign_role.post import UnassignRole


class RolesAndPermissionsApi(
    AssignRole,
    CreateRole,
    DeleteRole,
    EditRole,
    GetRole,
    GetRoles,
    ListUsersAssignedToRole,
    UnassignRole,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
