# coding: utf-8

"""
    REGNIFY HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: admin@regnify.com
    Generated by: https://openapi-generator.tech
"""

from regnify.paths.users_user_id_admin_change_user_password.put import AdminChangeUserPassword
from regnify.paths.users_change_user_password.put import ChangeUserPassword
from regnify.paths.users_.post import CreateUser
from regnify.paths.users_list_scopes.get import ListScopes
from regnify.paths.users_user_id.get import ReadUser
from regnify.paths.users_token.get import ReadUserMe
from regnify.paths.users_.get import ReadUsers
from regnify.paths.users_request_password_change.post import RequestPasswordChange
from regnify.paths.users_resend_invite.post import ResendInvite
from regnify.paths.users_user_id.put import UpdateUser


class UsersApi(
    AdminChangeUserPassword,
    ChangeUserPassword,
    CreateUser,
    ListScopes,
    ReadUser,
    ReadUserMe,
    ReadUsers,
    RequestPasswordChange,
    ResendInvite,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
