# coding: utf-8

"""
    REGNIFY HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: admin@regnify.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import regnify
from regnify.model.many_system_scope_out import ManySystemScopeOut
from regnify import configuration


class TestManySystemScopeOut(unittest.TestCase):
    """ManySystemScopeOut unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
