# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import regnify
from regnify.paths.users_request_password_change import post  # noqa: E501
from regnify import configuration, schemas, api_client

from .. import ApiTestMixin


class TestUsersRequestPasswordChange(ApiTestMixin, unittest.TestCase):
    """
    UsersRequestPasswordChange unit test stubs
        Request Password Change  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
